actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
attachLocalFile: false
avgRunTime: 2
avgRunTimeDisplay: 2 Seconds
bccRecipients: null
body: 'Hello ,


  Could you please review and provide your approval for the transfer of billing data.


  Please respond to udmg.emea@stonebranch.com with a message "Approved" or "Rejected"


  Regards,

  Stonebranch Ops Team

  '
ccRecipients: null
connection: email
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_email
firstRun: 2021-07-27 12:18:36 +0200
holdResources: false
lastRun: 2023-03-20 08:06:18 +0100
lastRunTime: 3
lastRunTimeDisplay: 3 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
listReportFormat: PDF
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 4
maxRunTimeDisplay: 4 Seconds
minRunTime: 1
minRunTimeDisplay: 1 Seconds
name: KM-EMAIL-APPROVAL
notes: []
opswiseGroups:
- Karthik Mohan
- KM-Job-as-Code
replyTo: null
report: null
reportVar: null
resPriority: 10
resolveNameImmediately: true
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 24
runTime: 55
startHeld: false
startHeldReason: null
subject: Claim Process Approval
summary: null
sysId: c30436dc97f24771bdb3ee22b840a0dd
template: null
templateVar: null
timeZonePref: -- System Default --
toRecipients: karthik.mohan@stonebranch.com
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskEmail
userEstimatedDuration: null
variables: []
version: 2
virtualResources: []
