actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
attachLocalFile: true
avgRunTime: 3
avgRunTimeDisplay: 3 Seconds
bccRecipients: null
body: 'Hello ,



  Please find the daily SLA breach report


  Regards,

  Stonebranch Ops Team

  '
ccRecipients: null
connection: KM Outgoing email
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_email
firstRun: 2021-09-27 16:57:51 +0200
holdResources: false
lastRun: 2022-09-14 16:05:30 +0200
lastRunTime: 2
lastRunTimeDisplay: 2 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
listReportFormat: PDF
localAttachment: email_attachment.txt
localAttachmentsPath: c:/email_attachments/
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 5
maxRunTimeDisplay: 5 Seconds
minRunTime: 2
minRunTimeDisplay: 2 Seconds
name: 'KM-EMAIL '
notes: []
opswiseGroups:
- Karthik Mohan
- KM-Job-as-Code
replyTo: null
report:
  groupName: null
  title: KM-SLA Breach
  userName: null
reportVar: null
resPriority: 10
resolveNameImmediately: true
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 6
runTime: 15
startHeld: false
startHeldReason: null
subject: Daily SLA Report
summary: null
sysId: ef05c29b548b42eb9259d2e4b62ab8b0
template: null
templateVar: null
timeZonePref: -- System Default --
toRecipients: udmg.emea@stonebranch.com
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskEmail
userEstimatedDuration: null
variables: []
version: 4
virtualResources: []
