actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
attachLocalFile: false
avgRunTime: 2
avgRunTimeDisplay: 2 Seconds
bccRecipients: null
body: 'Hi ,


  Workflow execution completed successfully.

  Please find the attached document for details.



  Regards,

  Operations Team.'
ccRecipients: null
connection: RKM Outgoing email
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_email
firstRun: 2021-11-24 11:27:54 +0100
holdResources: false
lastRun: 2022-07-15 13:45:17 +0200
lastRunTime: 3
lastRunTimeDisplay: 3 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
listReportFormat: PDF
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 3
maxRunTimeDisplay: 3 Seconds
minRunTime: 1
minRunTimeDisplay: 1 Seconds
name: KM-NOTIFY-END-CLAIM-PROCESS
notes: []
opswiseGroups:
- Karthik Mohan
- KM-Job-as-Code
replyTo: null
report:
  groupName: null
  title: Jobs-Report
  userName: kmohan
reportVar: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 3
runTime: 6
startHeld: false
startHeldReason: null
subject: End of Batch Notification - Bill Process
summary: Send email Notify end of billing process
sysId: 3965da1b3e1545debfabca87a94cfe29
template: null
templateVar: null
timeZonePref: -- System Default --
toRecipients: karthik.mohan@stonebranch.com
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskEmail
userEstimatedDuration: null
variables: []
version: 3
virtualResources: []
